In [ ]:
#Name: Sanskriti Lamsal
#StudentID: 10619390
#This work is mine. I didn't receive any external assistance for this project. 
#Project 2 Replacing Midterm 3

In [163]:
import numpy as np
array = np.loadtxt("/Users/sanskritilamsal/Desktop/matrix.txt", dtype='i', delimiter=' ')
print(array)

[[82 10 16 15 66]
 [91 28 98 43  4]
 [13 55 96 92 85]
 [92 96 49 80 94]
 [64 97 81 96 68]]


In [164]:
value = int(input("Please enter an integer:\n"))


Please enter an integer:
50


In [167]:
class Position:
    def __init__(self, first, second):
      self.first = first
      self.second = second


def printMaxSqaureSubMatrix(arr, kval):
        print("The k value is: ",kval)
        row = len(arr) #no.of rows
        if(row==0):
            return
       
        column = len(arr[0]) #no. of column
        if(column==0):
            return
        
        bit_array = [[0 for i in range(row)] for j in range(column)]
        sizes = [[0 for i in range(row)] for j in range(column)] #sizes matrix will keep track of the maximum submatrix number
        
        #bit array is created so that we can have a bool-type matrix
        
        for i in range(0,row): #fill rest of the matrix
            for j in range(0,column):
                if(arr[i][j] > kval):
                    bit_array[i][j] = 1 #setting val to 1 if value in arrayElem>kval
                else:
                    bit_array[i][j] = 0 #setting val to 1 if value in !(arrayElem>kval)        
        maximum = 0
        coordinates = []       
            
        for i in range(0,row): #fill rest of the matrix
            for j in range(0,column):
                if i==0 or j==0:                   
                    sizes[i][j] = bit_array[i][j]
                elif(bit_array[i][j] == 1):
                    sizes[i][j] = min(min(sizes[i][j-1],sizes[i-1][j]),sizes[i-1][j-1])+1
                if(sizes[i][j] >= maximum):  
                    if(sizes[i][j] > maximum): #reset the coordinates array
                        coordinates=[]
                        maximum = sizes[i][j]
                        coordinates.append((i+1,j+1))
                    else: 
                        coordinates.append((i+1,j+1))
                
        
        print("Maximum Submatrix size is: ", maximum)
        print("Bottom co-ordinates: ",coordinates)
        return maximum                
                 

                

printMaxSqaureSubMatrix(array, value)


The k value is:  50
Maximum Submatrix size is:  2
Bottom co-ordinates:  [(4, 5), (5, 2), (5, 5)]


2